openapi: 3.0.0
info:
  title: Stock API
  version: 0.0.1-SNAPSHOT
  description: Stock API
  license:
    name: Apache 2.0
servers:
  - url: 'http://localhost:9002'
paths:
  /stocks:
    get:
      summary: Get all stocks
      tags:
        - Stock
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StockResponse'
      operationId: get-stocks
      description: ''
  '/stocks/{itemIds}':
    parameters:
      - schema:
          type: array
          items:
            type: integer
            format: int64
        name: itemIds
        in: path
        description: |
          Item IDs
        required: true
    get:
      summary: Get stocks by item ids
      tags:
        - Stock
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StockResponse'
      operationId: get-stocks-by-item-ids
  /stocks/keep:
    post:
      summary: Keep stock
      operationId: post-stocks-keep
      responses:
        '200':
          description: OK
        '409':
          description: Not enough stocks
      description: Keep stocks
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/StockRequest'
components:
  schemas:
    StockRequest:
      title: StockRequest
      type: object
      x-examples: {}
      description: The request of Stock
      x-tags:
        - Stock
      properties:
        itemId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
          minimum: 1
          maximum: 50
      required:
        - itemId
        - quantity
    StockResponse:
      title: StockResponse
      type: object
      x-examples: {}
      description: The reponse of Stock
      properties:
        itemId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
      required:
        - itemId
        - quantity
      x-tags:
        - Stock
