openapi: 3.0.0
info:
  title: Stock API
  version: 0.0.1-SNAPSHOT
  description: Stock API
  license:
    name: Apache 2.0
servers:
  - url: 'http://localhost:9003'
paths:
  '/carts/{cartId}':
    parameters:
      - schema:
          type: integer
          format: int64
        name: cartId
        in: path
        description: ''
        required: true
    get:
      summary: Get a cart by id
      tags:
        - Cart
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartResponse'
      operationId: get-cart-by-cartId
    post:
      summary: Add an item to a cart
      operationId: add-item
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartDetailResponse'
          headers: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCartRequest'
      tags:
        - Cart
  '/carts/{cartId}/detail':
    parameters:
      - schema:
          type: integer
          format: int32
        name: cartId
        in: path
        required: true
    get:
      summary: Get a cart detail by id
      tags:
        - Cart
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartDetailResponse'
      operationId: get-cart-detail-by-cartId
  /carts:
    post:
      summary: Create a cart
      operationId: carete-cart
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartResponse'
          headers:
            Location:
              schema:
                type: string
                format: uri
      tags:
        - Cart
  '/carts/{cartId}/items/{itemId}':
    parameters:
      - schema:
          type: integer
          format: int32
        name: cartId
        in: path
        required: true
      - schema:
          type: integer
          format: int32
        name: itemId
        in: path
        required: true
    delete:
      summary: ''
      operationId: remove-item
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartResponse'
      tags:
        - Cart
components:
  schemas:
    CartResponse:
      title: CartResponse
      type: object
      x-examples: {}
      properties:
        cartId:
          type: integer
          format: int64
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartResponseItem'
      required:
        - cartId
        - items
      x-tags:
        - Cart
    CartResponseItem:
      title: CartResponseItem
      type: object
      x-tags:
        - Cart
      properties:
        itemId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
    CartDetailResponse:
      title: CartDetailResponse
      type: object
      x-tags:
        - Cart
      properties:
        cartId:
          type: integer
          format: int64
        total:
          type: number
          format: double
        items:
          type: array
          items:
            $ref: '#/components/schemas/CartDetailResponseItem'
    CartDetailResponseItem:
      title: CartDetailResponseItem
      type: object
      properties:
        itemId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        name:
          type: string
          description: ''
        author:
          type: string
        unitPrice:
          type: number
          format: double
        release:
          type: string
          format: date
        image:
          type: string
          format: uri
      x-tags:
        - Cart
    UpdateCartRequest:
      title: UpdateCartRequest
      type: object
      properties:
        itemId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
      x-tags:
        - Cart
